### PR TITLE
[Fix] KeyError for invalid key access

### LINKED ISSUE #316: Non-existing key access should result in an error
```coffee
obj = {"bar": 1}
b = obj["foo"] # ERROR
```

The story should be stopped at line two and print a stack trace.

See also: https://github.com/storyscript/platform-engine/issues/315

### PR DESCRIPTION
**Pull request by mehtavishwa30**
Fixes #316

### CODE REVIEW

**Comment by judepereira** [comment]
@mehtavishwa30 Can you check why the tests are failing?

**Comment by mehtavishwa30** [comment]
Working on it! I am having trouble recognising which line is throwing the KeyError exception.

**Comment by judepereira** [comment]
>  I am having trouble recognising which line is throwing the KeyError exception.

Yea, that's a problem with the integration test runner. We built it on the fly, and has been very good so far. I would follow the following debug process:
1. Isolate which test is failing (the story which fails is printed to stdout)
2. Run this story as the first one in the entire suite
3. Put a breakpoint in the suite runner and debug :)

**Comment by mehtavishwa30** [comment]
Hey! 
Re-ran the test suite that was failing and debugged the code. The test results look fine now. Although, there are a few misses in the code coverage here. Can you please review? @judepereira

**Comment by judepereira** [comment]
Checking.

**Comment by judepereira** [comment]
@mehtavishwa30 The function you modified, `Resolver#dictionary` is not called at all. It's a stale function. I believe your earlier approach was correct, where you were throwing the exception here: https://github.com/storyscript/platform-engine/blob/9f78c883a4f3da41c781629d0a978765d7e234c6/asyncy/utils/Resolver.py#L52

**Comment by mehtavishwa30** [comment]
Thanks for your review @judepereira! Will look into it again and continue working on the previous approach.

**Comment by judepereira** [comment]
Closing in favour of #412.

**Pull request closed without merging**
