### PR TITLE
Database: adding fix for empty service on get_service_limits

### PR DESCRIPTION
**Pull request by TonyRice**
This fixes the following issue:

```
 Failed to bootstrap app ('NoneType' object is not subscriptable)
Traceback (most recent call last):
  File "/home/XXX/src/platform-engine/asyncy/Apps.py", line 127, in deploy_release
    await app.bootstrap()
  File "/home/XXX/src/platform-engine/asyncy/App.py", line 95, in bootstrap
    await self.start_services()
  File "/home/XXX/src/platform-engine/asyncy/App.py", line 167, in start_services
    raise exc
  File "/home/XXX/src/platform-engine/asyncy/processing/Services.py", line 510, in start_container
    return await Containers.start(story, line)
  File "/home/XXX/src/platform-engine/asyncy/Containers.py", line 167, in start
    await cls.create_and_start(story.app, line, service, container_name)
  File "/home/XXX/src/platform-engine/asyncy/Containers.py", line 99, in create_and_start
    container_configs=container_configs)
  File "/home/XXX/src/platform-engine/asyncy/Kubernetes.py", line 692, in create_pod
    volumes, container_configs)
  File "/home/XXX/src/platform-engine/asyncy/Kubernetes.py", line 573, in create_deployment
    service_name, tag)
  File "/home/XXX/src/platform-engine/asyncy/db/Database.py", line 217, in get_service_limits
    res = await con.fetchrow(query, service['uuid'], tag)
```

### CODE REVIEW

**Comment by anukul** [comment]
Weird.. `service` should not be `None`. I'll add an assertion there, and also rename the argument to `service_uuid`.
Can you attach your story?

**Comment by TonyRice** [comment]
This only happens to me locally because the service_usage table is empty for me. This will just return the default limits. Make any changes you need.

**Comment by anukul** [comment]
`service_usage` can be empty, `services` can't be. The traceback should improve once the pending PR is merged. Updating some more stuff in it today.

**Comment by TonyRice** [comment]
Just realized you have a pending PR

**Pull request closed without merging**
