### PR TITLE
Set release state to TEMP_DEPLOYMENT_FAILURE on internal errors

### PR DESCRIPTION
**Pull request by anukul**
See https://github.com/storyscript/platform-engine/issues/386

### CODE REVIEW

**Comment by judepereira** [comment]
@anukul database schema changes? Need to merge that first.

**Comment by anukul** [comment]
@judepereira https://github.com/storyscript/database/pull/81

**Comment by wilzbach** [comment]
> @anukul database schema changes? Need to merge that first.

That's why we should move the database schema in here ;-)

**Comment by judepereira** [comment]
@anukul can you also investigate why https://codecov.io/gh/storyscript/platform-engine/pull/388/diff#D1-501 is a partial?

**Comment by judepereira** [comment]
> That's why we should move the database schema in here ;-)

@wilzbach I don't think so. The db schema has a ton of RLS, which the engine has nothing to do with. If it were plain schema, it would be best to move it here.

**Comment by anukul** [comment]
@judepereira coverage fixed. (`elif` -> `if`)

**Comment by judepereira** [comment]
Isn't elif correct?

**Comment by anukul** [comment]
Not for 100% coverage :p
That branch isn't executed when the exception is not `StoryscriptError`, so `elif` only ever returns `True`, making it a partial.

**Comment by judepereira** [comment]
@anukul okay - waiting for the CLI to be rolled out.

**Pull request merged**
