### PR TITLE
Rebranding AsyncyError to StoryscriptError

### PR DESCRIPTION
**Pull request by TonyRice**

### CODE REVIEW

**Comment by TonyRice** [comment]
Tests are failing flake8 and pep8. I have the pep8 updates in another PR, and Ideally, I'd like to get this merged into master before I do that so there are fewer conflict fixes on my end.

**Comment by judepereira** [comment]
Run the pep8 formatter here too? I guess the conflicts are unavoidable :(


Cheers,
Jude Pereira

**Comment by TonyRice** [comment]
> Run the pep8 formatter here too? I guess the conflicts are unavoidable :( Cheers, Jude Pereira
> […](#)
> Op 28 jun. 2019 om 19:03 heeft Tony Rice ***@***.***> het volgende geschreven: Tests are failing flake8 and pep8. I have the pep8 updates in another PR, and Ideally, I'd like to get this merged into master before I do that so there are fewer conflict fixes on my end. — You are receiving this because your review was requested. Reply to this email directly, view it on GitHub, or mute the thread.

You're definitely right, I shouldn't have any problem fixing it. Formatting away now.

**Comment by TonyRice** [comment]
@judepereira should be all good now!

**Comment by judepereira** [comment]
@TonyRice your changes to ContainerSpecNotRegisteredError are not required, since `story` and `line` are properly assigned by the executor in Story.py. Anyway, no harm done :)

**Pull request merged**
